"""
EnergyPlus Output Parser
=========================
Parses .eso, .csv, and .err output files from EnergyPlus simulations
into clean pandas DataFrames for analysis.
"""

import re
from pathlib import Path
from typing import Optional

import pandas as pd
import numpy as np
from loguru import logger


class EnergyPlusParser:
    """
    Parses EnergyPlus simulation output files.
    
    Supports:
    - .csv files generated by ReadVarsESO
    - .eso files (raw EnergyPlus output)
    - .err files (error/warning logs)
    """

    def __init__(self, output_dir: str):
        self.output_dir = Path(output_dir)

    # ------------------------------------------------------------------
    # CSV Parsing (primary method — relies on ReadVarsESO)
    # ------------------------------------------------------------------

    def parse_csv(self, filename: str = "eplusout.csv") -> pd.DataFrame:
        """
        Parse the EnergyPlus CSV output into a clean DataFrame.
        
        Returns:
            DataFrame with DateTimeIndex and clean column names.
        """
        csv_path = self.output_dir / filename
        if not csv_path.exists():
            logger.error(f"CSV file not found: {csv_path}")
            raise FileNotFoundError(f"CSV not found: {csv_path}")

        df = pd.read_csv(csv_path)

        # Clean column names — strip whitespace
        df.columns = [col.strip() for col in df.columns]

        # Parse the Date/Time column if present
        if "Date/Time" in df.columns:
            df = self._parse_datetime_column(df)

        logger.info(f"Parsed CSV with {len(df)} rows and {len(df.columns)} columns")
        return df

    def _parse_datetime_column(self, df: pd.DataFrame) -> pd.DataFrame:
        """Parse E+ Date/Time format (MM/DD HH:MM:SS) into proper datetime index."""
        try:
            # EnergyPlus uses format like " 01/01  01:00:00"
            dt_strings = df["Date/Time"].str.strip()
            # Add a reference year
            dt_strings = "2024/" + dt_strings
            df.index = pd.to_datetime(dt_strings, format="%Y/%m/%d  %H:%M:%S", errors="coerce")
            df.index.name = "datetime"
            df = df.drop(columns=["Date/Time"])
        except Exception as e:
            logger.warning(f"Could not parse Date/Time column: {e}")
        return df

    # ------------------------------------------------------------------
    # Timeseries extraction
    # ------------------------------------------------------------------

    def get_timeseries(
        self,
        variable: str,
        zone: Optional[str] = None,
        freq: Optional[str] = None,
        csv_filename: str = "eplusout.csv",
    ) -> pd.Series:
        """
        Extract a specific variable timeseries from the output.
        
        Args:
            variable: Part of the column name to match (case-insensitive).
            zone: Optional zone name to filter by.
            freq: Optional resample frequency (e.g., '1H', '1D').
        
        Returns:
            pd.Series with the matched variable data.
        """
        df = self.parse_csv(csv_filename)

        # Find matching columns
        matches = []
        for col in df.columns:
            col_lower = col.lower()
            var_match = variable.lower() in col_lower
            zone_match = (zone is None) or (zone.lower() in col_lower)
            if var_match and zone_match:
                matches.append(col)

        if not matches:
            raise ValueError(
                f"No column matching variable='{variable}', zone='{zone}'. "
                f"Available columns: {list(df.columns)}"
            )

        if len(matches) > 1:
            logger.warning(f"Multiple matches found: {matches}. Using first.")

        series = df[matches[0]].astype(float)
        series.name = matches[0]

        if freq:
            series = series.resample(freq).mean()

        return series

    # ------------------------------------------------------------------
    # KPI Computation
    # ------------------------------------------------------------------

    def compute_kpis(self, csv_filename: str = "eplusout.csv") -> dict:
        """
        Compute key performance indicators from simulation output.
        
        Returns:
            Dictionary with total_kwh, peak_kw, avg_pmv, comfort_hours_pct, etc.
        """
        df = self.parse_csv(csv_filename)
        kpis = {}

        # --- Total energy (kWh) ---
        energy_cols = [c for c in df.columns if "electricity" in c.lower() or "energy" in c.lower()]
        if energy_cols:
            # E+ reports energy in Joules — convert to kWh
            total_joules = sum(df[col].sum() for col in energy_cols)
            kpis["total_kwh"] = total_joules / 3_600_000  # J -> kWh
            kpis["energy_columns_used"] = energy_cols
        else:
            kpis["total_kwh"] = None
            logger.warning("No energy columns found in output")

        # --- Peak demand (kW) ---
        if energy_cols:
            # Approximate: max energy in any 15-min interval converted to kW
            timestep_hours = 0.25  # 15-minute timesteps
            peak_kwh = max(df[col].max() / 3_600_000 for col in energy_cols)
            kpis["peak_kw"] = peak_kwh / timestep_hours
        else:
            kpis["peak_kw"] = None

        # --- PMV (thermal comfort) ---
        pmv_cols = [c for c in df.columns if "pmv" in c.lower() or "fanger" in c.lower()]
        if pmv_cols:
            pmv_data = df[pmv_cols[0]].astype(float)
            kpis["avg_pmv"] = pmv_data.mean()
            kpis["max_pmv"] = pmv_data.max()
            kpis["min_pmv"] = pmv_data.min()
            # Comfort hours: PMV within [-0.5, +0.5]
            comfort_mask = (pmv_data >= -0.5) & (pmv_data <= 0.5)
            kpis["comfort_hours_pct"] = (comfort_mask.sum() / len(pmv_data)) * 100
        else:
            kpis["avg_pmv"] = None
            kpis["comfort_hours_pct"] = None
            logger.warning("No PMV columns found in output")

        # --- Zone temperatures ---
        temp_cols = [c for c in df.columns if "zone mean air temp" in c.lower()]
        if temp_cols:
            all_temps = pd.concat([df[col] for col in temp_cols], axis=1)
            kpis["avg_zone_temp_c"] = all_temps.mean().mean()
            kpis["min_zone_temp_c"] = all_temps.min().min()
            kpis["max_zone_temp_c"] = all_temps.max().max()
        else:
            kpis["avg_zone_temp_c"] = None

        logger.info(f"Computed KPIs: {kpis}")
        return kpis

    # ------------------------------------------------------------------
    # Error log parsing
    # ------------------------------------------------------------------

    def parse_error_log(self, max_lines: int = 100) -> dict:
        """
        Parse the EnergyPlus error log file.
        
        Returns:
            Dict with counts of warnings, severe errors, and fatal errors,
            plus the raw text of the last N lines.
        """
        err_path = self.output_dir / "eplusout.err"
        if not err_path.exists():
            return {"exists": False, "text": "Error log not found."}

        text = err_path.read_text(encoding="utf-8", errors="replace")
        lines = text.splitlines()

        result = {
            "exists": True,
            "total_lines": len(lines),
            "warnings": sum(1 for l in lines if "** Warning **" in l),
            "severe_errors": sum(1 for l in lines if "** Severe  **" in l),
            "fatal_errors": sum(1 for l in lines if "**  Fatal  **" in l),
            "last_lines": "\n".join(lines[-max_lines:]),
        }

        if result["fatal_errors"] > 0:
            logger.error(f"EnergyPlus had {result['fatal_errors']} fatal errors!")
        elif result["severe_errors"] > 0:
            logger.warning(f"EnergyPlus had {result['severe_errors']} severe errors")

        return result

    # ------------------------------------------------------------------
    # Latest timestep data (for real-time loop)
    # ------------------------------------------------------------------

    def get_latest_timestep(self, csv_filename: str = "eplusout.csv") -> dict:
        """
        Get the most recent timestep's data from the simulation output.
        Used by the closed-loop agent to read 'live' sensor values.
        
        Returns:
            Dict with variable names as keys and latest values.
        """
        df = self.parse_csv(csv_filename)
        if df.empty:
            return {"error": "No data available"}

        latest = df.iloc[-1]
        return {
            "timestamp": str(latest.name) if hasattr(latest, "name") else "unknown",
            "data": latest.to_dict(),
        }
